### ISSUE TITLE
Issue-further styling

### ISSUE THREAD

**Issue by lind0118** [lind0118/cocode#14]
Automated Review Comments
Issues in README.md:
  - (1, 'Line exceeds 80 characters')
Issues in package-lock.json:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in package.json:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src/App.js:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
Issues in src/components/MainContent.js:
  - (1, 'Hardcoded string found')
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
Issues in src/pages/Editor.js:
  - (2, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')

**Comment by brandonabeal110** [comment]
I got it.
