### ISSUE TITLE
Issue-final styling

### ISSUE THREAD

**Issue by lind0118** [lind0118/cocode#16]
Automated Review Comments
Issues in src/App.js:
  - (10, 'Hardcoded string found')
Issues in src/components/Client.js:
  - (1, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src/containers/Editor.js:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
Issues in src/containers/Home.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
Issues in src/index.css:
  - (10, 'Hardcoded string found')
Issues in src/index.js:
  - (1, 'Hardcoded string found')
  - (7, 'Hardcoded string found')

**Comment by brandonabeal110** [comment]
I got it.
