### ISSUE TITLE
Issue-Initialize project using Create React App

### ISSUE THREAD

**Issue by lind0118** [lind0118/cocode#2]
Automated Review Comments
Issues in .gitignore:
  - (2, 'Line exceeds 80 characters')
Issues in README.md:
  - (6, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
Issues in public/index.html:
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
Issues in public/manifest.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in src/App.js:
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in src/App.test.js:
  - (5, 'Hardcoded string found')
Issues in src/index.css:
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in src/index.js:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/logo.svg:
  - (2, 'Line exceeds 80 characters')
Issues in src/reportWebVitals.js:
  - (4, 'Line exceeds 80 characters')

**Comment by brandonabeal110** [comment]
I got it.
