### ISSUE TITLE
Issue-init

### ISSUE THREAD

**Issue by lind0118** [lind0118/cocode#6]
Automated Review Comments
Issues in README.md:
  - (5, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
Issues in server.js:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
Issues in src/Actions.js:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/App.js:
  - (11, 'Hardcoded string found')
Issues in src/components/Client.js:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in src/components/Editor.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
Issues in src/index.css:
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in src/index.js:
  - (2, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in src/pages/EditorPage.js:
  - (2, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
Issues in src/pages/Home.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
Issues in src/socket.js:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')

**Comment by brandonabeal110** [comment]
I got it.
