### ISSUE TITLE
Issue-Revert "init"

This reverts commit 9a73fe9ea62f6ded0b91f3051c961ae0272d929e.

### ISSUE THREAD

**Issue by lind0118** [lind0118/cocode#8]
Automated Review Comments
Issues in README.md:
  - (6, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
Issues in src/App.js:
  - (36, 'Hardcoded string found')
Issues in src/index.css:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in src/index.js:
  - (2, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (15, 'Hardcoded string found')

**Comment by brandonabeal110** [comment]
I got it.
